//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilepsia.NET
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Epilepsia_TP_Entities : DbContext
    {
        public Epilepsia_TP_Entities()
            : base("name=Epilepsia_TP_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Alerta> Alerta { get; set; }
        public DbSet<Registro_Episodio> Registro_Episodio { get; set; }
        public DbSet<Telefono> Telefono { get; set; }
        public DbSet<Token_Login> Token_Login { get; set; }
        public DbSet<Tratamiento> Tratamiento { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
