//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilepsia.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicamento
    {
        public long Id { get; set; }
        public Nullable<long> PacienteId { get; set; }
        public string Nombre { get; set; }
        public int PeriodicidadHoras { get; set; }
        public bool Activo { get; set; }
        public Nullable<System.DateTime> UltimaVez { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
