//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilepsia.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Telefono
    {
        public long Id { get; set; }
        public string Numero { get; set; }
        public long Id_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
