//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilepsia.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamiento
    {
        public long Id { get; set; }
        public System.DateTime Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Fin { get; set; }
        public string Medicamento { get; set; }
        public string Toma_Cada { get; set; }
        public string Dosis { get; set; }
        public long Id_Usuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
