//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Epilepsia.NET
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Alerta = new HashSet<Alerta>();
            this.Alerta1 = new HashSet<Alerta>();
            this.Registro_Episodio = new HashSet<Registro_Episodio>();
            this.Telefono = new HashSet<Telefono>();
            this.Tratamiento = new HashSet<Tratamiento>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> Edad { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Tipo_Usuario { get; set; }
    
        public virtual ICollection<Alerta> Alerta { get; set; }
        public virtual ICollection<Alerta> Alerta1 { get; set; }
        public virtual ICollection<Registro_Episodio> Registro_Episodio { get; set; }
        public virtual ICollection<Telefono> Telefono { get; set; }
        public virtual Token_Login Token_Login { get; set; }
        public virtual ICollection<Tratamiento> Tratamiento { get; set; }
    }
}
